# 🚀 Jellyfin Analytics Dashboard - SIMPLE VERSION
# One-command deployment: docker compose up
# Dashboard: http://localhost:3000

services:
  jellyfin-analytics:
    build: .
    container_name: jellyfin-analytics
    restart: unless-stopped
    user: '1000:1000' # Run as UID:GID 1000:1000 for Linux compatibility
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/analytics.db
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-JellyfinAnalytics2024SecureDefaultKey!ChangeInProduction}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # Use default bridge network for Windows compatibility
    # Linux users can use host networking with: docker run --network host ...
